import type { CareerPackage } from '@/types/domain';

export const FALLBACK_PACKAGES: CareerPackage[] = [
  {
    id: 1,
    name: 'Premium Full Package',
    nameAr: 'الباقة المتكاملة المميزة',
    description:
      'A premium bilingual career package covering your CV, cover letter, LinkedIn profile, job application file, and job application service.',
    price: 800,
    features: [
      'CV (English + Arabic) — 300 AED',
      'Cover Letter (English + Arabic) — 200 AED',
      'LinkedIn Profile Optimization — 150 AED',
      'Job Application File — 50 AED',
      'Job Application — 100 AED',
    ],
    featuresAr: [
      'السيرة الذاتية (العربية + الإنجليزية) — 300 درهم',
      'خطاب التقديم (العربية + الإنجليزية) — 200 درهم',
      'تحسين ملف لينكدإن — 150 درهم',
      'ملف التقديم على الوظائف — 50 درهم',
      'خدمة التقديم على الوظائف — 100 درهم',
    ],
    deliveryDays: 10,
    maxRevisions: 3,
    sortOrder: 1,
    images: [
      {
        id: 1,
        path: '/images/packages/golden-signature-package.png',
        url: '/images/packages/golden-signature-package.png',
        altText: 'Premium Full Package',
        isPrimary: true,
        displayOrder: 1,
      },
    ],
    offers: [
      {
        id: 1,
        name: '50% OFF (Limited Offer)',
        nameAr: 'خصم 50% (عرض محدود)',
        description: 'Limited-time 50% discount on the package base price.',
        discountPercentage: 50,
      },
    ],
    buyerCount: 142,
    ratingAverage: 4.9,
    ratingCount: 38,
  },
  {
    id: 2,
    name: 'Full Package',
    nameAr: 'الباقة المتكاملة',
    description:
      'A bilingual package combining your CV, cover letter, and LinkedIn profile optimization in one coordinated service.',
    price: 650,
    features: [
      'CV (English + Arabic) — 300 AED',
      'Cover Letter (English + Arabic) — 200 AED',
      'LinkedIn Profile Optimization — 150 AED',
    ],
    featuresAr: [
      'السيرة الذاتية (العربية + الإنجليزية) — 300 درهم',
      'خطاب التقديم (العربية + الإنجليزية) — 200 درهم',
      'تحسين ملف لينكدإن — 150 درهم',
    ],
    deliveryDays: 7,
    maxRevisions: 2,
    sortOrder: 2,
    images: [
      {
        id: 2,
        path: '/images/packages/career-excellence-package.png',
        url: '/images/packages/career-excellence-package.png',
        altText: 'Full Package',
        isPrimary: true,
        displayOrder: 1,
      },
    ],
    offers: [
      {
        id: 2,
        name: '50% OFF (Limited Offer)',
        nameAr: 'خصم 50% (عرض محدود)',
        description: 'Limited-time 50% discount on the package base price.',
        discountPercentage: 50,
      },
    ],
    buyerCount: 96,
    ratingAverage: 4.8,
    ratingCount: 24,
  },
  {
    id: 3,
    name: 'Professional Package',
    nameAr: 'الباقة الاحترافية',
    description:
      'A focused CV and matching cover letter in either English or Arabic, based on your preferred language.',
    price: 250,
    features: [
      'CV (English or Arabic) — 150 AED',
      'Cover Letter (English or Arabic) — 100 AED',
    ],
    featuresAr: [
      'السيرة الذاتية (العربية أو الإنجليزية) — 150 درهم',
      'خطاب التقديم (العربية أو الإنجليزية) — 100 درهم',
    ],
    deliveryDays: 5,
    maxRevisions: 1,
    sortOrder: 3,
    images: [
      {
        id: 3,
        path: '/images/packages/professional-distinction-package.png',
        url: '/images/packages/professional-distinction-package.png',
        altText: 'Professional Package',
        isPrimary: true,
        displayOrder: 1,
      },
    ],
    offers: [
      {
        id: 3,
        name: '50% OFF (Limited Offer)',
        nameAr: 'خصم 50% (عرض محدود)',
        description: 'Limited-time 50% discount on the package base price.',
        discountPercentage: 50,
      },
    ],
    buyerCount: 75,
    ratingAverage: 4.9,
    ratingCount: 19,
  },
  {
    id: 4,
    name: 'Professional CV',
    description:
      'A standalone professional CV writing and optimization service focused on clarity, structure, and career relevance.',
    price: 199,
    features: [
      'Professional CV writing and optimization',
      'ATS-conscious content structure',
      'Clear experience and achievement positioning',
    ],
    deliveryDays: 5,
    maxRevisions: 2,
    sortOrder: 4,
    images: [
      {
        id: 4,
        path: '/images/packages/professional-cv.png',
        url: '/images/packages/professional-cv.png',
        altText: 'Professional CV',
        isPrimary: true,
        displayOrder: 1,
      },
    ],
    offers: [],
    buyerCount: 210,
    ratingAverage: 4.9,
    ratingCount: 52,
  },
  {
    id: 5,
    name: 'LinkedIn Profile Optimization',
    description:
      'A standalone professional LinkedIn profile optimization service for a clearer, more consistent professional presence.',
    price: 149,
    features: [
      'Headline and About section optimization',
      'Experience section refinement',
      'Practical profile improvement guidance',
    ],
    deliveryDays: 4,
    maxRevisions: 1,
    sortOrder: 5,
    images: [
      {
        id: 5,
        path: '/images/packages/linkedin-profile-optimization.png',
        url: '/images/packages/linkedin-profile-optimization.png',
        altText: 'LinkedIn Profile Optimization',
        isPrimary: true,
        displayOrder: 1,
      },
    ],
    offers: [],
    buyerCount: 130,
    ratingAverage: 4.8,
    ratingCount: 31,
  },
  {
    id: 6,
    name: 'Job Application Service',
    description:
      'Professional job-application support for organizing opportunities, tailoring documents, and preparing a clear submission workflow.',
    price: 249,
    features: [
      'Target opportunity organization',
      'Job application document support',
      'Clear submission workflow and checklist',
    ],
    deliveryDays: 7,
    maxRevisions: 2,
    sortOrder: 6,
    images: [
      {
        id: 6,
        path: '/images/packages/job-application-service.png',
        url: '/images/packages/job-application-service.png',
        altText: 'Job Application Service',
        isPrimary: true,
        displayOrder: 1,
      },
    ],
    offers: [],
    buyerCount: 64,
    ratingAverage: 4.7,
    ratingCount: 15,
  },
];
