import type { CareerPackage } from '@/types/domain';

export const FALLBACK_PACKAGES: CareerPackage[] = [
  {
    id: 1,
    name: 'Golden Signature Package',
    description:
      'A complete, coordinated career-document suite for presenting one clear professional story across every application touchpoint.',
    price: 799,
    features: [
      'Professional CV',
      'Cover Letter',
      'LinkedIn Profile Optimization',
      'Job Application File',
    ],
    deliveryDays: 10,
    maxRevisions: 3,
    sortOrder: 1,
    images: [
      {
        id: 1,
        path: '/images/packages/golden-signature-package.png',
        url: '/images/packages/golden-signature-package.png',
        altText: 'Golden Signature Package',
        isPrimary: true,
        displayOrder: 1,
      },
    ],
    offers: [],
    buyerCount: 142,
    ratingAverage: 4.9,
    ratingCount: 38,
  },
  {
    id: 2,
    name: 'Career Excellence Package',
    description:
      'A coordinated CV, cover letter, and professional profile package designed to keep your positioning consistent.',
    price: 499,
    features: [
      'Professional CV',
      'Cover Letter',
      'LinkedIn Profile Optimization',
    ],
    deliveryDays: 7,
    maxRevisions: 2,
    sortOrder: 2,
    images: [
      {
        id: 2,
        path: '/images/packages/career-excellence-package.png',
        url: '/images/packages/career-excellence-package.png',
        altText: 'Career Excellence Package',
        isPrimary: true,
        displayOrder: 1,
      },
    ],
    offers: [],
    buyerCount: 96,
    ratingAverage: 4.8,
    ratingCount: 24,
  },
  {
    id: 3,
    name: 'Professional Distinction Package',
    description:
      'A focused CV and matching cover letter pair for a clear, consistent professional presentation.',
    price: 299,
    features: ['Professional CV', 'Cover Letter'],
    deliveryDays: 5,
    maxRevisions: 1,
    sortOrder: 3,
    images: [
      {
        id: 3,
        path: '/images/packages/professional-distinction-package.png',
        url: '/images/packages/professional-distinction-package.png',
        altText: 'Professional Distinction Package',
        isPrimary: true,
        displayOrder: 1,
      },
    ],
    offers: [],
    buyerCount: 75,
    ratingAverage: 4.9,
    ratingCount: 19,
  },
  {
    id: 4,
    name: 'Professional CV',
    description:
      'A standalone professional CV writing and optimization service focused on clarity, structure, and career relevance.',
    price: 199,
    features: [
      'Professional CV writing and optimization',
      'ATS-conscious content structure',
      'Clear experience and achievement positioning',
    ],
    deliveryDays: 5,
    maxRevisions: 2,
    sortOrder: 4,
    images: [
      {
        id: 4,
        path: '/images/packages/professional-cv.png',
        url: '/images/packages/professional-cv.png',
        altText: 'Professional CV',
        isPrimary: true,
        displayOrder: 1,
      },
    ],
    offers: [],
    buyerCount: 210,
    ratingAverage: 4.9,
    ratingCount: 52,
  },
  {
    id: 5,
    name: 'LinkedIn Profile Optimization',
    description:
      'A standalone professional LinkedIn profile optimization service for a clearer, more consistent professional presence.',
    price: 149,
    features: [
      'Headline and About section optimization',
      'Experience section refinement',
      'Practical profile improvement guidance',
    ],
    deliveryDays: 4,
    maxRevisions: 1,
    sortOrder: 5,
    images: [
      {
        id: 5,
        path: '/images/packages/linkedin-profile-optimization.png',
        url: '/images/packages/linkedin-profile-optimization.png',
        altText: 'LinkedIn Profile Optimization',
        isPrimary: true,
        displayOrder: 1,
      },
    ],
    offers: [],
    buyerCount: 130,
    ratingAverage: 4.8,
    ratingCount: 31,
  },
  {
    id: 6,
    name: 'Job Application Service',
    description:
      'Professional job-application support for organizing opportunities, tailoring documents, and preparing a clear submission workflow.',
    price: 249,
    features: [
      'Target opportunity organization',
      'Job application document support',
      'Clear submission workflow and checklist',
    ],
    deliveryDays: 7,
    maxRevisions: 2,
    sortOrder: 6,
    images: [
      {
        id: 6,
        path: '/images/packages/job-application-service.png',
        url: '/images/packages/job-application-service.png',
        altText: 'Job Application Service',
        isPrimary: true,
        displayOrder: 1,
      },
    ],
    offers: [],
    buyerCount: 64,
    ratingAverage: 4.7,
    ratingCount: 15,
  },
];
